# Generated by Django 5.1.4 on 2025-01-20 12:47

import django.core.validators
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350, verbose_name='Kitob nomi')),
                ('pages', models.PositiveIntegerField(verbose_name='Sahifalar soni')),
                ('year', models.DateField(verbose_name='Chop etilgan sana')),
                ('price', models.PositiveIntegerField(verbose_name="Narxi (so'm)")),
                ('book_image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[220, 320], upload_to='image/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'bmp', 'webp'])], verbose_name='Kitob rasmi')),
                ('genre', models.CharField(choices=[('Diniy', 'Diniy'), ('Jadid Adabiyoti', 'Jadid Adabiyoti'), ('Zamonaviy', 'Zamonaviy'), ('Ishqiy', 'Ishqiy')], max_length=20, verbose_name='Janr')),
                ('author', models.CharField(max_length=225, verbose_name='Muallif')),
                ('isbn', models.CharField(max_length=13, verbose_name='ISBN')),
                ('bio', models.TextField(verbose_name='Annotatsiya')),
            ],
        ),
        migrations.CreateModel(
            name='botsavemodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message_type', models.CharField(default='text', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(default='In progress', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TextModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('code', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
