# Generated by Django 5.1.3 on 2024-12-06 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0006_sotish'),
    ]

    operations = [
        migrations.AddField(
            model_name='sotish',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homeapp.books'),
        ),
    ]
