# Generated by Django 5.1.3 on 2024-12-24 13:52

import django.core.validators
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0008_bookcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, verbose_name='Kitob nomi')),
                ('pages', models.PositiveIntegerField(verbose_name='Sahifalar soni')),
                ('year', models.DateField(verbose_name='Chop etilgan sana')),
                ('price', models.PositiveIntegerField(verbose_name="Narxi (so'm)")),
                ('book_image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 400], upload_to='image/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'bmp', 'webp'])], verbose_name='Kitob rasmi')),
                ('genre', models.CharField(choices=[('Diniy', 'Diniy'), ('Jadid Adabiyoti', 'Jadid Adabiyoti'), ('Zamonaviy', 'Zamonaviy'), ('Ishqiy', 'Ishqiy')], max_length=20, verbose_name='Janr')),
                ('author', models.CharField(max_length=225, verbose_name='Muallif')),
                ('isbn', models.CharField(max_length=13, verbose_name='ISBN')),
                ('bio', models.TextField(verbose_name='Annotatsiya')),
            ],
        ),
        migrations.DeleteModel(
            name='Bookcomment',
        ),
        migrations.RemoveField(
            model_name='sotish',
            name='book',
        ),
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.DeleteModel(
            name='Sotish',
        ),
    ]
