# Generated by Django 5.1.4 on 2024-12-25 13:04

import django.core.validators
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0014_alter_addbook_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='book_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to='image/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Kitob rasmi'),
        ),
        migrations.AlterField(
            model_name='addbook',
            name='title',
            field=models.CharField(max_length=350, verbose_name='Kitob nomi'),
        ),
    ]
