# Generated by Django 5.1.4 on 2024-12-25 13:22

import django.core.validators
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0016_alter_addbook_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='book_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[220, 320], upload_to='image/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'bmp', 'webp'])], verbose_name='Kitob rasmi'),
        ),
    ]
