# Generated by Django 5.1.4 on 2025-01-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0019_task_textmodel_delete_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='In progress', max_length=50),
        ),
    ]
